# 这些 section 下的内容会出现在首页和归档页
mainSections = ["post"]
# RSS 输出完整正文
rssFullContent = true
favicon        = "img/favicon.png"

# accepted values: "default", "lastmod"
# default: Hugo 默认排序
# lastmod: 按最后更新时间倒序
SortBy              = "default"

[footer]
    since      = 2020
    customText = "基于 Hugo 与 Stack 主题构建"

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "🍥"
    subtitle = "一个使用 Hugo 与 Stack 主题搭建的中文示例站点。"
    avatar   = "img/avatar.png"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "本文采用 CC BY-NC-SA 4.0 许可协议"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## 评论系统
[comments]
    enabled  = true
    provider = "disqus"

    # 更多可选配置见主题默认参数文件
    # 按需复制到这里覆盖即可
